### ISSUE TITLE
Libaries

### ISSUE THREAD

**Issue by littleyoda** [seaniefs/WT32-SC01-Exp#1]
I would like to try your code.
Could you tell me which Libraries you use?

**Comment by seaniefs** [comment]
Updated the README accordingly.  AFAIK it's the only custom library used.

Please ensure that you set it up using the instructions present in Demo_3D_cube_SS7796_ESPI.ino - use the pinout detailed at the top of the file.

Hope that helps!

Any problems let me know, but might have to wait until after Christmas Day! :)

**Comment by littleyoda** [comment]
Unfortunately, I did not get it to run.
The display only flashes. No reaction to touches.

Are we talking about the same thing?
https://www.seeedstudio.com/ESP32-Development-board-WT32-SC01-p-4735.html

I was just wondering about your statement regarding pin layout.

**Comment by seaniefs** [comment]
Yes, that's the one.

Added the User_Setup.h you'll need (see TFT_eSPI/User_Setup.h) - hope that helps!

Also please see ArduinoSettings.png.

**Comment by littleyoda** [comment]
Great ... it works now for me.
Thanks a lot

**Comment by littleyoda** [comment]
I forked your repository and added Platformio-Support.
https://github.com/littleyoda/WT32-SC01-Exp
