### ISSUE TITLE
Tips on how to load the built binary to the device?

### ISSUE THREAD

**Issue by tmclane** [seaniefs/WT32-SC01-Exp#3]
Any chance someone could add a README with some steps on how to build and run this on a WT32-SC01?

**Comment by Lumics** [comment]
I do not really have time but basically you could look for one of the example within the mentioned library (Bodmer/TFT_eSPI) like this: https://github.com/Bodmer/TFT_eSPI/tree/master/examples/320%20x%20240/TFT_Clock

Then you replace the files with the one from this repo and it should work.

Feel free to ask more specific questions

**Comment by tmclane** [comment]
I completely understand the no time thing!

I was able to get it to compile no problem.  I just don't understand what settings to put in the Arduino IDE in order to actually flash it to the device.  Is it just a generic ESP32 board basically?

**Comment by Lumics** [comment]
I use platformIO and not the Arduino IDE, Therefore I cannot really tell you the exact settings for it. Yes it is just a ESP32, depending on the version with 4MB Flash or 16MB Flash.

**Comment by tmclane** [comment]
I suppose you don't happen to have an example simple platformio project handy then that would just work?
This one just has an INO file which I assumed meant Arduino IDE.

I do like platformio much better and build my projects with it usually.

**Comment by Lumics** [comment]
You can use this project: https://github.com/Lumics/ESP32_TTGO_T1_HumiGadget_Sensirion and add the TFT_eSPI folder from this repo to lib. In the platformio.ini you have to change it to sth like this:


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Library options
lib_deps = 
	knolleary/PubSubClient@^2.8
	nkolban/ESP32 BLE Arduino@^1.0.1

upload_port = /dev/cu.usbserial-0200CAE6

monitor_port = /dev/cu.usbserial-0200CAE6
monitor_flags=
    --parity
    N
    --filter
    printable

board_build.partitions = no_ota.csv

**Comment by tmclane** [comment]
Thank you for the tip!  I did get it to build and run on the device but haven't gotten the spinning cube to display.  I'll keep messing with it and perhaps link a working fork once I figure it out.
